import bpy
class ShaderNodeuv_map_tile_pattern_2(bpy.types.ShaderNodeCustomGroup):
    bl_name='ShaderNodeuv_map_tile_pattern_2'
    bl_label='uv_map_tile_pattern_2'
    bl_icon='NONE'

    def init(self, context):
        self.getNodetree(self.name + '_node_tree')
        self.inputs['Vector'].default_value=[0,0,0]
        self.inputs['HAS_Vector'].default_value=0
        self.inputs['HAS_Vector'].hide=True
        self.inputs['scale'].default_value=1

    def update(self):
        if self.inputs['Vector'].is_linked:
            self.inputs['HAS_Vector'].default_value=1
        else:    
            self.inputs['HAS_Vector'].default_value=0
            pass

    def value_set(self, obj, path, value):
        if '.' in path:
            path_prop, path_attr = path.rsplit('.', 1)
            prop = obj.path_resolve(path_prop)
        else:
            prop = obj
            path_attr = path
        setattr(prop, path_attr, value)

    def createNodetree(self, name) :
        self.node_tree = bpy.data.node_groups.new(name, 'ShaderNodeTree')
        #Nodes
        self.addNode('NodeGroupInput', { 'name':'GroupInput'  })
        self.addNode('NodeGroupOutput', { 'name':'GroupOutput'  })
        self.addNode('ShaderNodeTexCoord', { 'name':'Node0'  })
        self.addNode('ShaderNodeMixRGB', { 'name':'Node1'  })
        self.addNode('ShaderNodeValue', { 'name':'Node4' ,'outputs[0].default_value':0.5  })
        self.addNode('ShaderNodeValue', { 'name':'Node5' ,'outputs[0].default_value':0.25  })
        self.addNode('ShaderNodeValue', { 'name':'Node6' ,'outputs[0].default_value':0  })
        self.addNode('ShaderNodeValue', { 'name':'Node7' ,'outputs[0].default_value':0  })
        self.addNode('ShaderNodeValue', { 'name':'Node8' ,'outputs[0].default_value':1  })
        self.addNode('ShaderNodeValue', { 'name':'Node9' ,'outputs[0].default_value':0  })
        self.addNode('ShaderNodeValue', { 'name':'Node11' ,'outputs[0].default_value':0.25  })
        self.addNode('ShaderNodeValue', { 'name':'Node12' ,'outputs[0].default_value':-1  })
        self.addNode('ShaderNodeValue', { 'name':'Node13' ,'outputs[0].default_value':3  })
        self.addNode('ShaderNodeValue', { 'name':'Node14' ,'outputs[0].default_value':0.5  })
        self.addNode('ShaderNodeValue', { 'name':'Node15' ,'outputs[0].default_value':2  })
        self.addNode('ShaderNodeValue', { 'name':'Node16' ,'outputs[0].default_value':4  })
        self.addNode('ShaderNodeValue', { 'name':'Node17' ,'outputs[0].default_value':2.25  })
        self.addNode('ShaderNodeValue', { 'name':'Node18' ,'outputs[0].default_value':-0.25  })
        self.addNode('ShaderNodeValue', { 'name':'Node19' ,'outputs[0].default_value':1  })
        self.addNode('ShaderNodeSeparateXYZ', { 'name':'Node20'  })
        self.addNode('ShaderNodeMath', { 'name':'Node21' ,'operation':'MULTIPLY' })
        self.addNode('ShaderNodeSeparateXYZ', { 'name':'Node22'  })
        self.addNode('ShaderNodeMath', { 'name':'Node23' ,'operation':'MULTIPLY' })
        self.addNode('ShaderNodeCombineXYZ', { 'name':'Node24'  })
        self.addNode('ShaderNodeSeparateXYZ', { 'name':'Node25'  })
        self.addNode('ShaderNodeMath', { 'name':'Node26' ,'inputs[1].default_value':0.5 ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node27' ,'inputs[1].default_value':0.5 ,'operation':'ROUND' })
        self.addNode('ShaderNodeMath', { 'name':'Node28' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeSeparateXYZ', { 'name':'Node29'  })
        self.addNode('ShaderNodeMath', { 'name':'Node30' ,'inputs[1].default_value':0.5 ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node31' ,'inputs[1].default_value':0.5 ,'operation':'ROUND' })
        self.addNode('ShaderNodeMath', { 'name':'Node32' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node33' ,'operation':'DIVIDE' })
        self.addNode('ShaderNodeMath', { 'name':'Node34' ,'inputs[1].default_value':0.5 ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node35' ,'operation':'ROUND' })
        self.addNode('ShaderNodeMath', { 'name':'Node36' ,'operation':'DIVIDE' })
        self.addNode('ShaderNodeMath', { 'name':'Node37' ,'inputs[1].default_value':0.5 ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node38' ,'operation':'ROUND' })
        self.addNode('ShaderNodeMath', { 'name':'Node39' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node40' ,'operation':'LESS_THAN' })
        self.addNode('ShaderNodeMath', { 'name':'Node41' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node42' ,'operation':'ABSOLUTE' })
        self.addNode('ShaderNodeMath', { 'name':'Node43' ,'inputs[1].default_value':0.000001 ,'operation':'GREATER_THAN' })
        self.addNode('ShaderNodeMath', { 'name':'Node44' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node45' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node46' ,'operation':'ABSOLUTE' })
        self.addNode('ShaderNodeMath', { 'name':'Node47' ,'inputs[1].default_value':0.000001 ,'operation':'LESS_THAN' })
        self.addNode('ShaderNodeMath', { 'name':'Node48' ,'operation':'GREATER_THAN' })
        self.addNode('ShaderNodeMath', { 'name':'Node49' ,'operation':'ADD' })
        self.addNode('ShaderNodeMath', { 'name':'Node50' ,'inputs[1].default_value':0.999 ,'operation':'GREATER_THAN' })
        self.addNode('ShaderNodeMath', { 'name':'Node51' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node52' ,'operation':'ABSOLUTE' })
        self.addNode('ShaderNodeMath', { 'name':'Node53' ,'inputs[1].default_value':0.000001 ,'operation':'GREATER_THAN' })
        self.addNode('ShaderNodeMixRGB', { 'name':'Node54'  })
        self.addNode('ShaderNodeMath', { 'name':'Node55' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node56' ,'operation':'ABSOLUTE' })
        self.addNode('ShaderNodeMath', { 'name':'Node57' ,'inputs[1].default_value':0.000001 ,'operation':'GREATER_THAN' })
        self.addNode('ShaderNodeMath', { 'name':'Node58' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node59' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node60' ,'operation':'ABSOLUTE' })
        self.addNode('ShaderNodeMath', { 'name':'Node61' ,'inputs[1].default_value':0.000001 ,'operation':'LESS_THAN' })
        self.addNode('ShaderNodeMath', { 'name':'Node62' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node63' ,'operation':'ABSOLUTE' })
        self.addNode('ShaderNodeMath', { 'name':'Node64' ,'inputs[1].default_value':0.000001 ,'operation':'GREATER_THAN' })
        self.addNode('ShaderNodeMixRGB', { 'name':'Node65'  })
        self.addNode('ShaderNodeMath', { 'name':'Node66' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node67' ,'operation':'ABSOLUTE' })
        self.addNode('ShaderNodeMath', { 'name':'Node68' ,'inputs[1].default_value':0.000001 ,'operation':'LESS_THAN' })
        self.addNode('ShaderNodeMath', { 'name':'Node69' ,'operation':'ADD' })
        self.addNode('ShaderNodeMath', { 'name':'Node70' ,'operation':'MULTIPLY' })
        self.addNode('ShaderNodeMath', { 'name':'Node71' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node72' ,'operation':'MODULO' })
        self.addNode('ShaderNodeMath', { 'name':'Node73' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node74' ,'operation':'MODULO' })
        self.addNode('ShaderNodeSeparateXYZ', { 'name':'Node75'  })
        self.addNode('ShaderNodeMath', { 'name':'Node76' ,'operation':'MULTIPLY' })
        self.addNode('ShaderNodeMath', { 'name':'Node77' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node78' ,'inputs[1].default_value':0.5 ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node79' ,'inputs[1].default_value':0.5 ,'operation':'ROUND' })
        self.addNode('ShaderNodeMath', { 'name':'Node80' ,'operation':'DIVIDE' })
        self.addNode('ShaderNodeMath', { 'name':'Node81' ,'operation':'MULTIPLY' })
        self.addNode('ShaderNodeMath', { 'name':'Node82' ,'inputs[1].default_value':0.5 ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node83' ,'operation':'ROUND' })
        self.addNode('ShaderNodeSeparateXYZ', { 'name':'Node84'  })
        self.addNode('ShaderNodeMath', { 'name':'Node85' ,'operation':'DIVIDE' })
        self.addNode('ShaderNodeMath', { 'name':'Node86' ,'inputs[1].default_value':0.5 ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node87' ,'operation':'ROUND' })
        self.addNode('ShaderNodeMath', { 'name':'Node88' ,'operation':'MULTIPLY' })
        self.addNode('ShaderNodeCombineXYZ', { 'name':'Node89'  })
        self.addNode('ShaderNodeMath', { 'name':'Node90' ,'operation':'ADD' })
        self.addNode('ShaderNodeMath', { 'name':'Node91' ,'operation':'MULTIPLY' })
        self.addNode('ShaderNodeMath', { 'name':'Node92' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node93' ,'operation':'MODULO' })
        self.addNode('ShaderNodeMath', { 'name':'Node94' ,'operation':'MODULO' })
        self.addNode('ShaderNodeSeparateXYZ', { 'name':'Node95'  })
        self.addNode('ShaderNodeMath', { 'name':'Node96' ,'operation':'MULTIPLY' })
        self.addNode('ShaderNodeMath', { 'name':'Node97' ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node98' ,'inputs[1].default_value':0.5 ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node99' ,'inputs[1].default_value':0.5 ,'operation':'ROUND' })
        self.addNode('ShaderNodeMath', { 'name':'Node100' ,'operation':'DIVIDE' })
        self.addNode('ShaderNodeMath', { 'name':'Node101' ,'operation':'MULTIPLY' })
        self.addNode('ShaderNodeMath', { 'name':'Node102' ,'inputs[1].default_value':0.5 ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node103' ,'operation':'ROUND' })
        self.addNode('ShaderNodeMath', { 'name':'Node104' ,'operation':'ADD' })
        self.addNode('ShaderNodeSeparateXYZ', { 'name':'Node105'  })
        self.addNode('ShaderNodeMath', { 'name':'Node106' ,'operation':'DIVIDE' })
        self.addNode('ShaderNodeMath', { 'name':'Node107' ,'inputs[1].default_value':0.5 ,'operation':'SUBTRACT' })
        self.addNode('ShaderNodeMath', { 'name':'Node108' ,'operation':'ROUND' })
        self.addNode('ShaderNodeMath', { 'name':'Node109' ,'operation':'MULTIPLY' })
        self.addNode('ShaderNodeCombineXYZ', { 'name':'Node110'  })
        self.addNode('ShaderNodeMixRGB', { 'name':'Node111'  })
        self.addNode('ShaderNodeMixRGB', { 'name':'Node112'  })
        self.addNode('ShaderNodeMixRGB', { 'name':'Node113'  })
        self.addNode('ShaderNodeMixRGB', { 'name':'Node114'  })
        self.addNode('ShaderNodeMath', { 'name':'Node115' ,'operation':'MODULO' })
        self.addNode('ShaderNodeMath', { 'name':'Node116' ,'operation':'MODULO' })
        self.addNode('ShaderNodeCombineXYZ', { 'name':'Node117'  })
        #Sockets
        self.addSocket(False, 'NodeSocketVector', 'Vector')
        self.addSocket(False, 'NodeSocketFloatFactor', 'HAS_Vector')
        self.addSocket(False, 'NodeSocketFloat', 'scale')
        self.addSocket(True, 'NodeSocketVector', 'UV')
        self.addSocket(True, 'NodeSocketVector', 'cellID')
        self.addSocket(True, 'NodeSocketFloat', 'brick_width')
        self.addSocket(True, 'NodeSocketFloat', 'brick_height')
        self.addSocket(True, 'NodeSocketFloat', 'tile_mask')
        #Links
        self.innerLink('nodes["GroupInput"].outputs[1]', 'nodes["Node1"].inputs[0]')
        self.innerLink('nodes["Node0"].outputs[3]', 'nodes["Node1"].inputs[1]')
        self.innerLink('nodes["GroupInput"].outputs[0]', 'nodes["Node1"].inputs[2]')
        self.innerLink('nodes["Node1"].outputs[0]', 'nodes["Node20"].inputs[0]')
        self.innerLink('nodes["Node20"].outputs[0]', 'nodes["Node21"].inputs[0]')
        self.innerLink('nodes["GroupInput"].outputs[2]', 'nodes["Node21"].inputs[1]')
        self.innerLink('nodes["Node1"].outputs[0]', 'nodes["Node22"].inputs[0]')
        self.innerLink('nodes["Node22"].outputs[1]', 'nodes["Node23"].inputs[0]')
        self.innerLink('nodes["GroupInput"].outputs[2]', 'nodes["Node23"].inputs[1]')
        self.innerLink('nodes["Node21"].outputs[0]', 'nodes["Node24"].inputs[0]')
        self.innerLink('nodes["Node23"].outputs[0]', 'nodes["Node24"].inputs[1]')
        self.innerLink('nodes["Node9"].outputs[0]', 'nodes["Node24"].inputs[2]')
        self.innerLink('nodes["Node24"].outputs[0]', 'nodes["Node25"].inputs[0]')
        self.innerLink('nodes["Node25"].outputs[0]', 'nodes["Node26"].inputs[0]')
        self.innerLink('nodes["Node26"].outputs[0]', 'nodes["Node27"].inputs[0]')
        self.innerLink('nodes["Node25"].outputs[0]', 'nodes["Node28"].inputs[0]')
        self.innerLink('nodes["Node27"].outputs[0]', 'nodes["Node28"].inputs[1]')
        self.innerLink('nodes["Node24"].outputs[0]', 'nodes["Node29"].inputs[0]')
        self.innerLink('nodes["Node29"].outputs[1]', 'nodes["Node30"].inputs[0]')
        self.innerLink('nodes["Node30"].outputs[0]', 'nodes["Node31"].inputs[0]')
        self.innerLink('nodes["Node29"].outputs[1]', 'nodes["Node32"].inputs[0]')
        self.innerLink('nodes["Node31"].outputs[0]', 'nodes["Node32"].inputs[1]')
        self.innerLink('nodes["Node28"].outputs[0]', 'nodes["Node33"].inputs[0]')
        self.innerLink('nodes["Node11"].outputs[0]', 'nodes["Node33"].inputs[1]')
        self.innerLink('nodes["Node33"].outputs[0]', 'nodes["Node34"].inputs[0]')
        self.innerLink('nodes["Node34"].outputs[0]', 'nodes["Node35"].inputs[0]')
        self.innerLink('nodes["Node32"].outputs[0]', 'nodes["Node36"].inputs[0]')
        self.innerLink('nodes["Node11"].outputs[0]', 'nodes["Node36"].inputs[1]')
        self.innerLink('nodes["Node36"].outputs[0]', 'nodes["Node37"].inputs[0]')
        self.innerLink('nodes["Node37"].outputs[0]', 'nodes["Node38"].inputs[0]')
        self.innerLink('nodes["Node35"].outputs[0]', 'nodes["Node39"].inputs[0]')
        self.innerLink('nodes["Node38"].outputs[0]', 'nodes["Node39"].inputs[1]')
        self.innerLink('nodes["Node39"].outputs[0]', 'nodes["Node40"].inputs[0]')
        self.innerLink('nodes["Node8"].outputs[0]', 'nodes["Node40"].inputs[1]')
        self.innerLink('nodes["Node40"].outputs[0]', 'nodes["Node41"].inputs[0]')
        self.innerLink('nodes["Node7"].outputs[0]', 'nodes["Node41"].inputs[1]')
        self.innerLink('nodes["Node41"].outputs[0]', 'nodes["Node42"].inputs[0]')
        self.innerLink('nodes["Node42"].outputs[0]', 'nodes["Node43"].inputs[0]')
        self.innerLink('nodes["Node35"].outputs[0]', 'nodes["Node44"].inputs[0]')
        self.innerLink('nodes["Node38"].outputs[0]', 'nodes["Node44"].inputs[1]')
        self.innerLink('nodes["Node44"].outputs[0]', 'nodes["Node45"].inputs[0]')
        self.innerLink('nodes["Node12"].outputs[0]', 'nodes["Node45"].inputs[1]')
        self.innerLink('nodes["Node45"].outputs[0]', 'nodes["Node46"].inputs[0]')
        self.innerLink('nodes["Node46"].outputs[0]', 'nodes["Node47"].inputs[0]')
        self.innerLink('nodes["Node44"].outputs[0]', 'nodes["Node48"].inputs[0]')
        self.innerLink('nodes["Node12"].outputs[0]', 'nodes["Node48"].inputs[1]')
        self.innerLink('nodes["Node47"].outputs[0]', 'nodes["Node49"].inputs[0]')
        self.innerLink('nodes["Node48"].outputs[0]', 'nodes["Node49"].inputs[1]')
        self.innerLink('nodes["Node49"].outputs[0]', 'nodes["Node50"].inputs[0]')
        self.innerLink('nodes["Node50"].outputs[0]', 'nodes["Node51"].inputs[0]')
        self.innerLink('nodes["Node7"].outputs[0]', 'nodes["Node51"].inputs[1]')
        self.innerLink('nodes["Node51"].outputs[0]', 'nodes["Node52"].inputs[0]')
        self.innerLink('nodes["Node52"].outputs[0]', 'nodes["Node53"].inputs[0]')
        self.innerLink('nodes["Node43"].outputs[0]', 'nodes["Node54"].inputs[0]')
        self.innerLink('nodes["Node43"].outputs[0]', 'nodes["Node54"].inputs[1]')
        self.innerLink('nodes["Node53"].outputs[0]', 'nodes["Node54"].inputs[2]')
        self.innerLink('nodes["Node54"].outputs[0]', 'nodes["Node55"].inputs[0]')
        self.innerLink('nodes["Node7"].outputs[0]', 'nodes["Node55"].inputs[1]')
        self.innerLink('nodes["Node55"].outputs[0]', 'nodes["Node56"].inputs[0]')
        self.innerLink('nodes["Node56"].outputs[0]', 'nodes["Node57"].inputs[0]')
        self.innerLink('nodes["Node35"].outputs[0]', 'nodes["Node58"].inputs[0]')
        self.innerLink('nodes["Node38"].outputs[0]', 'nodes["Node58"].inputs[1]')
        self.innerLink('nodes["Node58"].outputs[0]', 'nodes["Node59"].inputs[0]')
        self.innerLink('nodes["Node13"].outputs[0]', 'nodes["Node59"].inputs[1]')
        self.innerLink('nodes["Node59"].outputs[0]', 'nodes["Node60"].inputs[0]')
        self.innerLink('nodes["Node60"].outputs[0]', 'nodes["Node61"].inputs[0]')
        self.innerLink('nodes["Node61"].outputs[0]', 'nodes["Node62"].inputs[0]')
        self.innerLink('nodes["Node7"].outputs[0]', 'nodes["Node62"].inputs[1]')
        self.innerLink('nodes["Node62"].outputs[0]', 'nodes["Node63"].inputs[0]')
        self.innerLink('nodes["Node63"].outputs[0]', 'nodes["Node64"].inputs[0]')
        self.innerLink('nodes["Node57"].outputs[0]', 'nodes["Node65"].inputs[0]')
        self.innerLink('nodes["Node64"].outputs[0]', 'nodes["Node65"].inputs[1]')
        self.innerLink('nodes["Node57"].outputs[0]', 'nodes["Node65"].inputs[2]')
        self.innerLink('nodes["Node65"].outputs[0]', 'nodes["Node66"].inputs[0]')
        self.innerLink('nodes["Node8"].outputs[0]', 'nodes["Node66"].inputs[1]')
        self.innerLink('nodes["Node66"].outputs[0]', 'nodes["Node67"].inputs[0]')
        self.innerLink('nodes["Node67"].outputs[0]', 'nodes["Node68"].inputs[0]')
        self.innerLink('nodes["Node15"].outputs[0]', 'nodes["Node69"].inputs[0]')
        self.innerLink('nodes["Node32"].outputs[0]', 'nodes["Node69"].inputs[1]')
        self.innerLink('nodes["Node35"].outputs[0]', 'nodes["Node70"].inputs[0]')
        self.innerLink('nodes["Node11"].outputs[0]', 'nodes["Node70"].inputs[1]')
        self.innerLink('nodes["Node69"].outputs[0]', 'nodes["Node71"].inputs[0]')
        self.innerLink('nodes["Node70"].outputs[0]', 'nodes["Node71"].inputs[1]')
        self.innerLink('nodes["Node71"].outputs[0]', 'nodes["Node72"].inputs[0]')
        self.innerLink('nodes["Node14"].outputs[0]', 'nodes["Node72"].inputs[1]')
        self.innerLink('nodes["Node14"].outputs[0]', 'nodes["Node73"].inputs[0]')
        self.innerLink('nodes["Node72"].outputs[0]', 'nodes["Node73"].inputs[1]')
        self.innerLink('nodes["Node28"].outputs[0]', 'nodes["Node74"].inputs[0]')
        self.innerLink('nodes["Node11"].outputs[0]', 'nodes["Node74"].inputs[1]')
        self.innerLink('nodes["Node24"].outputs[0]', 'nodes["Node75"].inputs[0]')
        self.innerLink('nodes["Node35"].outputs[0]', 'nodes["Node76"].inputs[0]')
        self.innerLink('nodes["Node11"].outputs[0]', 'nodes["Node76"].inputs[1]')
        self.innerLink('nodes["Node75"].outputs[1]', 'nodes["Node77"].inputs[0]')
        self.innerLink('nodes["Node76"].outputs[0]', 'nodes["Node77"].inputs[1]')
        self.innerLink('nodes["Node77"].outputs[0]', 'nodes["Node78"].inputs[0]')
        self.innerLink('nodes["Node78"].outputs[0]', 'nodes["Node79"].inputs[0]')
        self.innerLink('nodes["Node79"].outputs[0]', 'nodes["Node80"].inputs[0]')
        self.innerLink('nodes["Node14"].outputs[0]', 'nodes["Node80"].inputs[1]')
        self.innerLink('nodes["Node80"].outputs[0]', 'nodes["Node81"].inputs[0]')
        self.innerLink('nodes["Node15"].outputs[0]', 'nodes["Node81"].inputs[1]')
        self.innerLink('nodes["Node81"].outputs[0]', 'nodes["Node82"].inputs[0]')
        self.innerLink('nodes["Node82"].outputs[0]', 'nodes["Node83"].inputs[0]')
        self.innerLink('nodes["Node24"].outputs[0]', 'nodes["Node84"].inputs[0]')
        self.innerLink('nodes["Node84"].outputs[0]', 'nodes["Node85"].inputs[0]')
        self.innerLink('nodes["Node11"].outputs[0]', 'nodes["Node85"].inputs[1]')
        self.innerLink('nodes["Node85"].outputs[0]', 'nodes["Node86"].inputs[0]')
        self.innerLink('nodes["Node86"].outputs[0]', 'nodes["Node87"].inputs[0]')
        self.innerLink('nodes["Node87"].outputs[0]', 'nodes["Node88"].inputs[0]')
        self.innerLink('nodes["Node16"].outputs[0]', 'nodes["Node88"].inputs[1]')
        self.innerLink('nodes["Node83"].outputs[0]', 'nodes["Node89"].inputs[0]')
        self.innerLink('nodes["Node88"].outputs[0]', 'nodes["Node89"].inputs[1]')
        self.innerLink('nodes["Node9"].outputs[0]', 'nodes["Node89"].inputs[2]')
        self.innerLink('nodes["Node17"].outputs[0]', 'nodes["Node90"].inputs[0]')
        self.innerLink('nodes["Node28"].outputs[0]', 'nodes["Node90"].inputs[1]')
        self.innerLink('nodes["Node38"].outputs[0]', 'nodes["Node91"].inputs[0]')
        self.innerLink('nodes["Node18"].outputs[0]', 'nodes["Node91"].inputs[1]')
        self.innerLink('nodes["Node90"].outputs[0]', 'nodes["Node92"].inputs[0]')
        self.innerLink('nodes["Node91"].outputs[0]', 'nodes["Node92"].inputs[1]')
        self.innerLink('nodes["Node92"].outputs[0]', 'nodes["Node93"].inputs[0]')
        self.innerLink('nodes["Node14"].outputs[0]', 'nodes["Node93"].inputs[1]')
        self.innerLink('nodes["Node32"].outputs[0]', 'nodes["Node94"].inputs[0]')
        self.innerLink('nodes["Node11"].outputs[0]', 'nodes["Node94"].inputs[1]')
        self.innerLink('nodes["Node24"].outputs[0]', 'nodes["Node95"].inputs[0]')
        self.innerLink('nodes["Node38"].outputs[0]', 'nodes["Node96"].inputs[0]')
        self.innerLink('nodes["Node11"].outputs[0]', 'nodes["Node96"].inputs[1]')
        self.innerLink('nodes["Node95"].outputs[0]', 'nodes["Node97"].inputs[0]')
        self.innerLink('nodes["Node96"].outputs[0]', 'nodes["Node97"].inputs[1]')
        self.innerLink('nodes["Node97"].outputs[0]', 'nodes["Node98"].inputs[0]')
        self.innerLink('nodes["Node98"].outputs[0]', 'nodes["Node99"].inputs[0]')
        self.innerLink('nodes["Node99"].outputs[0]', 'nodes["Node100"].inputs[0]')
        self.innerLink('nodes["Node14"].outputs[0]', 'nodes["Node100"].inputs[1]')
        self.innerLink('nodes["Node100"].outputs[0]', 'nodes["Node101"].inputs[0]')
        self.innerLink('nodes["Node15"].outputs[0]', 'nodes["Node101"].inputs[1]')
        self.innerLink('nodes["Node101"].outputs[0]', 'nodes["Node102"].inputs[0]')
        self.innerLink('nodes["Node102"].outputs[0]', 'nodes["Node103"].inputs[0]')
        self.innerLink('nodes["Node8"].outputs[0]', 'nodes["Node104"].inputs[0]')
        self.innerLink('nodes["Node103"].outputs[0]', 'nodes["Node104"].inputs[1]')
        self.innerLink('nodes["Node24"].outputs[0]', 'nodes["Node105"].inputs[0]')
        self.innerLink('nodes["Node105"].outputs[1]', 'nodes["Node106"].inputs[0]')
        self.innerLink('nodes["Node11"].outputs[0]', 'nodes["Node106"].inputs[1]')
        self.innerLink('nodes["Node106"].outputs[0]', 'nodes["Node107"].inputs[0]')
        self.innerLink('nodes["Node107"].outputs[0]', 'nodes["Node108"].inputs[0]')
        self.innerLink('nodes["Node108"].outputs[0]', 'nodes["Node109"].inputs[0]')
        self.innerLink('nodes["Node16"].outputs[0]', 'nodes["Node109"].inputs[1]')
        self.innerLink('nodes["Node104"].outputs[0]', 'nodes["Node110"].inputs[0]')
        self.innerLink('nodes["Node109"].outputs[0]', 'nodes["Node110"].inputs[1]')
        self.innerLink('nodes["Node9"].outputs[0]', 'nodes["Node110"].inputs[2]')
        self.innerLink('nodes["Node68"].outputs[0]', 'nodes["Node111"].inputs[0]')
        self.innerLink('nodes["Node110"].outputs[0]', 'nodes["Node111"].inputs[1]')
        self.innerLink('nodes["Node89"].outputs[0]', 'nodes["Node111"].inputs[2]')
        self.innerLink('nodes["Node68"].outputs[0]', 'nodes["Node112"].inputs[0]')
        self.innerLink('nodes["Node6"].outputs[0]', 'nodes["Node112"].inputs[1]')
        self.innerLink('nodes["Node8"].outputs[0]', 'nodes["Node112"].inputs[2]')
        self.innerLink('nodes["Node68"].outputs[0]', 'nodes["Node113"].inputs[0]')
        self.innerLink('nodes["Node93"].outputs[0]', 'nodes["Node113"].inputs[1]')
        self.innerLink('nodes["Node73"].outputs[0]', 'nodes["Node113"].inputs[2]')
        self.innerLink('nodes["Node68"].outputs[0]', 'nodes["Node114"].inputs[0]')
        self.innerLink('nodes["Node94"].outputs[0]', 'nodes["Node114"].inputs[1]')
        self.innerLink('nodes["Node74"].outputs[0]', 'nodes["Node114"].inputs[2]')
        self.innerLink('nodes["Node113"].outputs[0]', 'nodes["Node115"].inputs[0]')
        self.innerLink('nodes["Node19"].outputs[0]', 'nodes["Node115"].inputs[1]')
        self.innerLink('nodes["Node114"].outputs[0]', 'nodes["Node116"].inputs[0]')
        self.innerLink('nodes["Node19"].outputs[0]', 'nodes["Node116"].inputs[1]')
        self.innerLink('nodes["Node115"].outputs[0]', 'nodes["Node117"].inputs[0]')
        self.innerLink('nodes["Node116"].outputs[0]', 'nodes["Node117"].inputs[1]')
        self.innerLink('nodes["Node9"].outputs[0]', 'nodes["Node117"].inputs[2]')
        self.innerLink('nodes["Node117"].outputs[0]', 'nodes["GroupOutput"].inputs[0]')
        self.innerLink('nodes["Node111"].outputs[0]', 'nodes["GroupOutput"].inputs[1]')
        self.innerLink('nodes["Node4"].outputs[0]', 'nodes["GroupOutput"].inputs[2]')
        self.innerLink('nodes["Node5"].outputs[0]', 'nodes["GroupOutput"].inputs[3]')
        self.innerLink('nodes["Node112"].outputs[0]', 'nodes["GroupOutput"].inputs[4]')
    def getNodetree(self, name):
        if bpy.data.node_groups.find(name)==-1:
            self.createNodetree(name)
        else:
            self.node_tree=bpy.data.node_groups[name]
                   
    def addSocket(self, is_output, sockettype, name):
        #for now duplicated socket names are not allowed
        if is_output==True:
            if self.node_tree.nodes['GroupOutput'].inputs.find(name)==-1:
                socket=self.node_tree.outputs.new(sockettype, name)
        elif is_output==False:
            if self.node_tree.nodes['GroupInput'].outputs.find(name)==-1:
                socket=self.node_tree.inputs.new(sockettype, name)
        return socket
       
    def addNode(self, nodetype, attrs):
        node=self.node_tree.nodes.new(nodetype)
        for attr in attrs:
            self.value_set(node, attr, attrs[attr])
        return node
   
    def getNode(self, nodename):
        if self.node_tree.nodes.find(nodename)>-1:
            return self.node_tree.nodes[nodename]
        return None
   
    def innerLink(self, socketin, socketout):
        SI=self.node_tree.path_resolve(socketin)
        SO=self.node_tree.path_resolve(socketout)
        self.node_tree.links.new(SI, SO)
       
    def free(self):
        if self.node_tree.users==1:
            bpy.data.node_groups.remove(self.node_tree, do_unlink=True)
 
 
 
